import { Inter } from "next/font/google";
import "./globals.css";
import Breadcrumbs from "@/components/BreadCrumbs";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Task 2 Breadcrumbs",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Navbar />
        <Breadcrumbs />
      </body>
    </html>
  );
}
